In [34]:
import numpy as np
import pandas as pd

In [35]:
!pip install -q opendatasets
import opendatasets as od
od.download('https://www.kaggle.com/datasets/grouplens/movielens-20m-dataset') #{"username":"nexus0621","key":"b05056a7db5052627b5a0f54029135c0"}

Skipping, found downloaded files in "./movielens-20m-dataset" (use force=True to force download)


In [36]:
import os

In [37]:
# Directory where the dataset is located
dataset_dir = './movielens-20m-dataset'

# List files in the dataset directory
files_in_dataset = os.listdir(dataset_dir)

# Filter CSV files
csv_files = [file for file in files_in_dataset if file.endswith('.csv')]

# Print CSV files
print("CSV files in the dataset:")
for csv_file in csv_files:
    print(csv_file)

CSV files in the dataset:
genome_tags.csv
tag.csv
movie.csv
link.csv
genome_scores.csv
rating.csv


In [38]:
movie_data = pd.read_csv('/content/movielens-20m-dataset/movie.csv')
movie_data

movieId                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
27273   131254        Kein Bund für's Leben (2007)   
27274   131256       Feuer, Eis & Dosenbier (2002)   
27275   131258                  The Pirates (2014)   
27276   131260                 Rentun Ruusu (2001)   
27277   131262                    Innocence (2014)   

                                            genres  
0      Adventure|Animation|Children|Comedy|Fantasy  
1                       Adventure|Children|Fantasy  
2                                   Comedy|Romance  
3                             Comedy|Drama|Romance  
4                                           Comedy  
...                                            ...  
27273                                       Comedy  
27274                                       Comedy  
27275                                    Adventure  
27276                           (no genres listed)  
27277                     Adventure|Fantasy|Horror  

[27278 rows x 3 columns]

In [39]:
movie = pd.read_csv('/content/movielens-20m-dataset/movie.csv')
ratings = pd.read_csv('/content/movielens-20m-dataset/rating.csv')

In [40]:
movie.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [41]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [42]:
movie.duplicated().sum()

0

In [43]:
ratings.duplicated().sum()

0

In [44]:
print(movie.shape)
print(ratings.shape)

(27278, 3)
(20000263, 4)


In [45]:
movie_ratings = ratings.merge(movie,on='movieId')

In [46]:
movie_ratings.drop('timestamp', axis=1, inplace=True)

In [47]:
movie_ratings

userId  movieId  rating  \
0              1        2     3.5   
1              5        2     3.0   
2             13        2     3.0   
3             29        2     3.0   
4             34        2     3.0   
...          ...      ...     ...   
20000258  138301   121017     3.5   
20000259  138301   121019     4.5   
20000260  138301   121021     4.5   
20000261  138406   110167     4.5   
20000262  138406   110510     4.5   

                                                      title  \
0                                            Jumanji (1995)   
1                                            Jumanji (1995)   
2                                            Jumanji (1995)   
3                                            Jumanji (1995)   
4                                            Jumanji (1995)   
...                                                     ...   
20000258                    The Gentleman from Epsom (1962)   
20000259                         The Great Spy Chase (1964)   
20000260                             Taxi for Tobruk (1961)   
20000261  Judge and the Assassin, The (Juge et l'assassi...   
20000262                                 Série noire (1979)   

                              genres  
0         Adventure|Children|Fantasy  
1         Adventure|Children|Fantasy  
2         Adventure|Children|Fantasy  
3         Adventure|Children|Fantasy  
4         Adventure|Children|Fantasy  
...                              ...  
20000258                Comedy|Crime  
20000259      Action|Comedy|Thriller  
20000260                   Drama|War  
20000261                 Crime|Drama  
20000262                   Film-Noir  

[20000263 rows x 5 columns]

In [48]:
print('The ratings dataset has', movie_ratings['userId'].nunique(), 'unique users')
print('The ratings dataset has', movie_ratings['movieId'].nunique(), 'unique movies')
print('The ratings dataset has', movie_ratings['rating'].nunique(), 'unique ratings')
# List of unique ratings
print('The unique ratings are', sorted(movie_ratings['rating'].unique()))

The ratings dataset has 138493 unique users
The ratings dataset has 26744 unique movies
The ratings dataset has 10 unique ratings
The unique ratings are [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]


In [49]:
#considering the users that have rated more than 50 movies
x = movie_ratings.groupby('userId').count()['rating'] > 1000
users= x[x].index#Boolean indexing

In [50]:
filtered_rating = movie_ratings[movie_ratings['userId'].isin(users)]

In [51]:
filtered_rating

userId  movieId  rating                                     title  \
8            116        2     2.0                            Jumanji (1995)   
20           156        2     5.0                            Jumanji (1995)   
39           298        2     3.0                            Jumanji (1995)   
85           572        2     3.5                            Jumanji (1995)   
89           586        2     3.0                            Jumanji (1995)   
...          ...      ...     ...                                       ...   
20000256  138301   113539     4.0  First Man, The (Le Premier Homme) (2011)   
20000257  138301   118856     4.0                     Paris by Night (2012)   
20000258  138301   121017     3.5           The Gentleman from Epsom (1962)   
20000259  138301   121019     4.5                The Great Spy Chase (1964)   
20000260  138301   121021     4.5                    Taxi for Tobruk (1961)   

                              genres  
8         Adventure|Children|Fantasy  
20        Adventure|Children|Fantasy  
39        Adventure|Children|Fantasy  
85        Adventure|Children|Fantasy  
89        Adventure|Children|Fantasy  
...                              ...  
20000256                       Drama  
20000257                 Crime|Drama  
20000258                Comedy|Crime  
20000259      Action|Comedy|Thriller  
20000260                   Drama|War  

[2801066 rows x 5 columns]

In [52]:
#considering the users that have rated more than 50 movies
x = movie_ratings.groupby('movieId').count()['rating'] > 1000
users= x[x].index#Boolean indexing

In [53]:
filtered_rating = movie_ratings[movie_ratings['userId'].isin(users)]

In [54]:
filtered_rating

userId  movieId  rating                         title  \
0              1        2     3.5                Jumanji (1995)   
1              5        2     3.0                Jumanji (1995)   
2             13        2     3.0                Jumanji (1995)   
3             29        2     3.0                Jumanji (1995)   
4             34        2     3.0                Jumanji (1995)   
...          ...      ...     ...                           ...   
19994197   68358    32090     0.5          Low Life, The (1995)   
19995161   71264    99222     2.5           Silent Night (2012)   
19995184   71530    90622     2.0           Campus Radio (2011)   
19996447   86332   118468     4.0  Mei and the Kittenbus (2002)   
19998514  112852   130878     3.0      Doppelgänger Paul (2012)   

                              genres  
0         Adventure|Children|Fantasy  
1         Adventure|Children|Fantasy  
2         Adventure|Children|Fantasy  
3         Adventure|Children|Fantasy  
4         Adventure|Children|Fantasy  
...                              ...  
19994197                       Drama  
19995161                      Horror  
19995184                Comedy|Drama  
19996447           Animation|Fantasy  
19998514          (no genres listed)  

[473193 rows x 5 columns]

In [55]:
subset = filtered_rating.sample(frac=0.2, random_state=42)

In [56]:
subset

userId  movieId  rating                                 title  \
12262646    2412     1120     4.0    People vs. Larry Flynt, The (1996)   
6740414     5791     2469     3.0          Peggy Sue Got Married (1986)   
12338184    2161     1586     4.0                      G.I. Jane (1997)   
4690441     4211       10     3.0                      GoldenEye (1995)   
11629309    8507     3481     3.0                  High Fidelity (2000)   
...          ...      ...     ...                                   ...   
8488767     3208     2313     4.5              Elephant Man, The (1980)   
324056      4006      296     4.0                   Pulp Fiction (1994)   
6580453     8961     1911     4.0                   Dr. Dolittle (1998)   
3335522     2580      780     5.0  Independence Day (a.k.a. ID4) (1996)   
4596128     2081     2985     4.0                        RoboCop (1987)   

                                      genres  
12262646                        Comedy|Drama  
6740414                         Comedy|Drama  
12338184                        Action|Drama  
4690441            Action|Adventure|Thriller  
11629309                Comedy|Drama|Romance  
...                                      ...  
8488767                                Drama  
324056           Comedy|Crime|Drama|Thriller  
6580453                               Comedy  
3335522     Action|Adventure|Sci-Fi|Thriller  
4596128   Action|Crime|Drama|Sci-Fi|Thriller  

[94639 rows x 5 columns]

In [57]:
print('The ratings dataset has', subset['userId'].nunique(), 'unique users')
print('The ratings dataset has', subset['movieId'].nunique(), 'unique movies')
print('The ratings dataset has', subset['rating'].nunique(), 'unique ratings')
# List of unique ratings
print('The unique ratings are', sorted(subset['rating'].unique()))

The ratings dataset has 3153 unique users
The ratings dataset has 7869 unique movies
The ratings dataset has 10 unique ratings
The unique ratings are [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]


In [58]:
# Create user-item matrix

matrix = subset.pivot_table(index='userId', columns='title', values='rating')
matrix.fillna(0, inplace=True)
matrix.head()

title   'Hellboy': The Seeds of Creation (2004)  'Round Midnight (1986)  \
userId                                                                    
1                                           0.0                     0.0   
2                                           0.0                     0.0   
3                                           0.0                     0.0   
4                                           0.0                     0.0   
5                                           0.0                     0.0   

title   'Til There Was You (1997)  'burbs, The (1989)  'night Mother (1986)  \
userId                                                                        
1                             0.0                 0.0                   0.0   
2                             0.0                 0.0                   0.0   
3                             0.0                 0.0                   0.0   
4                             0.0                 0.0                   0.0   
5                             0.0                 0.0                   0.0   

title   (500) Days of Summer (2009)  *batteries not included (1987)  \
userId                                                                
1                               0.0                             0.0   
2                               0.0                             0.0   
3                               0.0                             0.0   
4                               0.0                             0.0   
5                               0.0                             0.0   

title   ...And Justice for All (1979)  .45 (2006)  1-900 (06) (1994)  ...  \
userId                                                                ...   
1                                 0.0         0.0                0.0  ...   
2                                 0.0         0.0                0.0  ...   
3                                 0.0         0.0                0.0  ...   
4                                 0.0         0.0                0.0  ...   
5                                 0.0         0.0                0.0  ...   

title   Zoom (2006)  Zorba the Greek (Alexis Zorbas) (1964)  \
userId                                                        
1               0.0                                     0.0   
2               0.0                                     0.0   
3               0.0                                     0.0   
4               0.0                                     0.0   
5               0.0                                     0.0   

title   Zorro, the Gay Blade (1981)  Zulu (1964)  [REC] (2007)  [REC]² (2009)  \
userId                                                                          
1                               0.0          0.0           0.0            0.0   
2                               0.0          0.0           0.0            0.0   
3                               0.0          0.0           0.0            0.0   
4                               0.0          0.0           0.0            0.0   
5                               0.0          0.0           0.0            0.0   

title   eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
userId                                                                
1                   0.0         0.0                             0.0   
2                   0.0         0.0                             0.0   
3                   0.0         0.0                             0.0   
4                   0.0         0.0                             0.0   
5                   0.0         0.0                             0.0   

title   ¡Three Amigos! (1986)  
userId                         
1                         0.0  
2                         0.0  
3                         0.0  
4                         0.0  
5                         0.0  

[5 rows x 7868 columns]

In [59]:
movie_features = matrix.copy().fillna(0)

In [60]:
R = movie_features.values
print(R)
user_ratings_mean = np.mean(R, axis = 1)

R_demeaned = R - user_ratings_mean.reshape(-1, 1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [61]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)
sigma = np.diag(sigma)
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

In [62]:
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = movie_features.columns)
preds_df.loc[[1535]]

title  'Hellboy': The Seeds of Creation (2004)  'Round Midnight (1986)  \
1535                                 -0.000999               -0.000194   

title  'Til There Was You (1997)  'burbs, The (1989)  'night Mother (1986)  \
1535                   -0.003495           -0.034877             -0.004989   

title  (500) Days of Summer (2009)  *batteries not included (1987)  \
1535                     -0.000601                        0.000481   

title  ...And Justice for All (1979)  .45 (2006)  1-900 (06) (1994)  ...  \
1535                        0.001743   -0.000058           0.007893  ...   

title  Zoom (2006)  Zorba the Greek (Alexis Zorbas) (1964)  \
1535      0.000205                                0.020077   

title  Zorro, the Gay Blade (1981)  Zulu (1964)  [REC] (2007)  [REC]² (2009)  \
1535                     -0.000498     0.001368      0.005727      -0.012455   

title  eXistenZ (1999)  xXx (2002)  xXx: State of the Union (2005)  \
1535          0.024328   -0.043132                       -0.009011   

title  ¡Three Amigos! (1986)  
1535                0.004306  

[1 rows x 7868 columns]

In [65]:
df_movies = subset[['movieId','title']].copy()
df_ratings = ratings[['userId','movieId','rating']].copy()
df_movies = df_movies.drop_duplicates()
df_ratings = df_ratings.drop_duplicates()
df_movies.head()

movieId                               title
12262646     1120  People vs. Larry Flynt, The (1996)
6740414      2469        Peggy Sue Got Married (1986)
12338184     1586                    G.I. Jane (1997)
4690441        10                    GoldenEye (1995)
11629309     3481                High Fidelity (2000)

In [80]:
def recommend_movies(preds_df, userID, df_movies, original_ratings_df, num_recommendations=5):
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = preds_df.iloc[user_row_number].sort_values(ascending=False)
    user_data = original_ratings_df[original_ratings_df.userId == (userID)]
    user_full = user_data.merge(df_movies).sort_values(['rating'],ascending = False)

    recommendations = (df_movies[~df_movies['movieId'].isin(user_full['movieId'])]).merge(pd.DataFrame(sorted_user_predictions).reset_index()).rename(columns = {user_row_number: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num_recommendations]


    return user_full , recommendations

In [70]:
already_rated , predictions = recommend_movies(preds_df, 1535, df_movies, df_ratings, 10)

In [72]:
already_rated.head(10)

userId  movieId  rating                                      title
2     1535      908     4.5                  North by Northwest (1959)
9     1535     2762     4.5                    Sixth Sense, The (1999)
12    1535     3471     4.5  Close Encounters of the Third Kind (1977)
20    1535    53123     4.5                                Once (2006)
19    1535    46578     4.5                Little Miss Sunshine (2006)
22    1535    56367     4.5                                Juno (2007)
24    1535    63082     4.5                 Slumdog Millionaire (2008)
28    1535    94959     4.5                    Moonrise Kingdom (2012)
7     1535     2407     4.0                              Cocoon (1985)
4     1535     1396     4.0                            Sneakers (1992)

In [82]:
predictions

movieId                                              title  Predictions
362      2396                         Shakespeare in Love (1998)     0.878520
430      1210  Star Wars: Episode VI - Return of the Jedi (1983)     0.644232
69        780               Independence Day (a.k.a. ID4) (1996)     0.570887
679      2918                    Ferris Bueller's Day Off (1986)     0.508660
891      1073         Willy Wonka & the Chocolate Factory (1971)     0.487471
570      1193             One Flew Over the Cuckoo's Nest (1975)     0.459692
1109     4226                                     Memento (2000)     0.429421
2227     2683       Austin Powers: The Spy Who Shagged Me (1999)     0.389131
147      2671                                Notting Hill (1999)     0.380102
576      2502                                Office Space (1999)     0.379854